# Generated by Django 3.0.6 on 2020-06-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='書名', max_length=20, null=True, verbose_name='書籍名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='出版商')),
            ],
        ),
        migrations.CreateModel(
            name='UID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_pw', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=15)),
                ('gender', models.CharField(default=2, max_length=1)),
                ('user_byear', models.CharField(max_length=4)),
                ('user_bmonth', models.CharField(max_length=2)),
                ('user_bday', models.CharField(max_length=2)),
                ('user_city', models.CharField(choices=[['TP', 'Taipei'], ['TY', 'Taoyuang'], ['TC', 'Taichung'], ['TN', 'Tainan'], ['KS', 'Kaohsiung'], ['NA', 'Others']], max_length=2)),
                ('enable', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=25)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.UID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='書籍作者', max_length=15)),
                ('description', models.TextField(default='暫時無說明', verbose_name='書籍簡介')),
                ('year', models.PositiveIntegerField(default=2016, verbose_name='出版年')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='價格')),
                ('pmodel', models.ForeignKey(default='3', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainsite.PModel', verbose_name='書名')),
            ],
        ),
        migrations.CreateModel(
            name='PPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='書籍狀況', max_length=20)),
                ('url', models.URLField(default='https://i.ibb.co/5vmRTyz/d350c383c6311ba3-thumb-600.jpg')),
                ('product', models.ForeignKey(default='3', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainsite.Product')),
            ],
        ),
        migrations.AddField(
            model_name='pmodel',
            name='publishing',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainsite.Publishing'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_byear', models.CharField(max_length=4)),
                ('user_bmonth', models.CharField(max_length=2)),
                ('user_bday', models.CharField(max_length=2)),
                ('user_school', models.BooleanField(default=False)),
                ('user_email', models.CharField(max_length=25)),
                ('user_message', models.TextField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.UID')),
            ],
        ),
    ]
