# Generated by Django 3.0.6 on 2020-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='作者姓名', max_length=15, verbose_name='書籍作者'),
        ),
    ]
