# Generated by Django 3.0.6 on 2020-06-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200610_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pmodel',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='書名', max_length=20, null=True, verbose_name='書籍名稱'),
        ),
        migrations.AddField(
            model_name='product',
            name='publishing',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainsite.Publishing'),
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
    ]
