# Generated by Django 3.0.6 on 2020-06-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200610_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='UID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
