# Generated by Django 3.0.6 on 2020-06-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200616_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_email',
            new_name='u_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_message',
            new_name='u_message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_school',
            new_name='u_school',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_bday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_bmonth',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_byear',
        ),
        migrations.AddField(
            model_name='contact',
            name='u_birthday',
            field=models.DateField(null=True),
        ),
    ]
