# Generated by Django 3.0.6 on 2020-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20200616_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='u_email',
            field=models.CharField(max_length=25, verbose_name='聯絡方式（電子郵件）'),
        ),
    ]
