# Generated by Django 3.0.6 on 2020-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20200616_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='del_pass',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
