# Generated by Django 3.0.6 on 2020-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_contact_del_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='del_pass',
        ),
        migrations.AddField(
            model_name='contact',
            name='u_city',
            field=models.CharField(choices=[['TP', 'Taipei'], ['TY', 'Taoyuang'], ['TC', 'Taichung'], ['TN', 'Tainan'], ['KS', 'Kaohsiung'], ['NA', 'Others']], default=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='u_name',
            field=models.CharField(default=False, max_length=20, verbose_name='暱稱'),
        ),
    ]
