# Generated by Django 3.0.6 on 2020-06-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20200616_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='u_city',
            field=models.CharField(choices=[['TP', 'Taipei'], ['TY', 'Taoyuang'], ['TC', 'Taichung'], ['TN', 'Tainan'], ['KS', 'Kaohsiung'], ['NA', 'Others']], default=False, max_length=2, verbose_name='居住地'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='u_name',
            field=models.CharField(default='不知道要取什麼', max_length=20, verbose_name='暱稱'),
        ),
    ]
