# Generated by Django 3.0.6 on 2020-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20200616_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='u_city',
        ),
        migrations.AddField(
            model_name='contact',
            name='u_suggest',
            field=models.CharField(choices=[['1', '網站外觀'], ['2', '可用性'], ['3', '內容建議'], ['4', '帳號問題'], ['5', '權限請求'], ['NA', 'Others']], default=False, max_length=6, verbose_name='建議分類'),
        ),
    ]
